import { useState } from 'react'
import type { FormEvent, ReactNode } from 'react'
import { FiArrowRight, FiEye, FiEyeOff, FiLock, FiMail, FiUser } from 'react-icons/fi'
import { Link, Navigate, useLocation, useNavigate } from 'react-router-dom'
import logo from '../assets/logo/Screenshot 2026-10-04 011634.png'
import { useAuth } from './AuthContext'

function AuthShell({ children, eyebrow, title, intro }: { children: ReactNode; eyebrow: string; title: string; intro: string }) {
  return <main className="auth-page"><div className="auth-orbit auth-orbit-one" /><div className="auth-orbit auth-orbit-two" /><section className="auth-layout"><aside className="auth-intro"><Link to="/" className="auth-brand"><img src={logo} alt="Two Quill Stories" /><span>Two Quill<br /><em>Stories</em></span></Link><p className="auth-eyebrow">{eyebrow}</p><h1>{title}</h1><p>{intro}</p><Link className="auth-back-link" to="/">Return to the home page <FiArrowRight /></Link></aside><div className="auth-card">{children}</div></section></main>
}

function Field({ label, icon: Icon, type = 'text', value, onChange, placeholder, autoComplete, error }: any) {
  return <label className="auth-field"><span>{label}</span><div className="auth-input-wrap"><Icon aria-hidden="true" /><input aria-invalid={Boolean(error)} autoComplete={autoComplete} placeholder={placeholder} type={type} value={value} onChange={onChange} /></div>{error && <small>{error}</small>}</label>
}

export function LoginPage() {
  const { login, isAuthenticated } = useAuth(); const navigate = useNavigate(); const location = useLocation()
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [remember, setRemember] = useState(false); const [show, setShow] = useState(false); const [error, setError] = useState(''); const [submitting, setSubmitting] = useState(false)
  if (isAuthenticated) return <Navigate replace to="/" />
  const redirect = new URLSearchParams(location.search).get('redirect') || '/books'
  async function submit(event: FormEvent) { event.preventDefault(); setError(''); if (!email || !password) { setError('Enter your email and password.'); return } setSubmitting(true); try { await login({ email, password, remember }); navigate(redirect, { replace: true }) } catch (err: any) { setError(err.message) } finally { setSubmitting(false) } }
  return <AuthShell eyebrow="Welcome back" title="Return to the stories that stay with you." intro="Sign in to continue exploring the Two Quill Stories library and the worlds behind each page."><form className="auth-form" onSubmit={submit}><div className="auth-form-heading"><span>Member sign in</span><h2>Welcome back.</h2><p>Your reading journey is waiting.</p></div>{error && <div className="auth-alert" role="alert">{error}</div>}<Field autoComplete="email" error={!email && error ? 'Email is required.' : ''} icon={FiMail} label="Email address" onChange={(e: any) => setEmail(e.target.value)} placeholder="you@example.com" value={email} /><label className="auth-field"><span>Password</span><div className="auth-input-wrap"><FiLock aria-hidden="true" /><input autoComplete="current-password" placeholder="Your password" type={show ? 'text' : 'password'} value={password} onChange={(e) => setPassword(e.target.value)} /><button aria-label={show ? 'Hide password' : 'Show password'} className="password-toggle" onClick={() => setShow(!show)} type="button">{show ? <FiEyeOff /> : <FiEye />}</button></div></label><div className="auth-options"><label><input checked={remember} onChange={(event) => setRemember(event.target.checked)} type="checkbox" /> Remember me</label><span>Forgot password? Contact us</span></div><button className="auth-submit" disabled={submitting} type="submit">{submitting ? 'Signing you in…' : 'Sign in'} {!submitting && <FiArrowRight />}</button><p className="auth-switch">New to Two Quill Stories? <Link to="/register">Create an account</Link></p></form></AuthShell>
}

export function RegisterPage() {
  const { register, isAuthenticated } = useAuth(); const navigate = useNavigate(); const [form, setForm] = useState({ name: '', email: '', password: '', confirm: '' }); const [show, setShow] = useState(false); const [error, setError] = useState(''); const [submitting, setSubmitting] = useState(false)
  if (isAuthenticated) return <Navigate replace to="/" />
  const update = (key: string) => (event: any) => setForm((current) => ({ ...current, [key]: event.target.value }))
  async function submit(event: FormEvent) { event.preventDefault(); setError(''); if (!form.name || !form.email || !form.password || !form.confirm) return setError('Complete every field to create your account.'); if (form.password.length < 8 || !/[A-Z]/.test(form.password) || !/[a-z]/.test(form.password) || !/\d/.test(form.password)) return setError('Use 8+ characters with uppercase, lowercase, and a number.'); if (form.password !== form.confirm) return setError('Your passwords do not match.'); setSubmitting(true); try { await register({ name: form.name, email: form.email, password: form.password }); navigate('/books', { replace: true }) } catch (err: any) { setError(err.message) } finally { setSubmitting(false) } }
  return <AuthShell eyebrow="Begin your journey" title="Make a little room for remarkable stories." intro="Create your reader account and unlock the full Two Quill Stories experience, from the library to the author’s world."><form className="auth-form" onSubmit={submit}><div className="auth-form-heading"><span>Create account</span><h2>Join the story.</h2><p>A calm place for curious readers.</p></div>{error && <div className="auth-alert" role="alert">{error}</div>}<Field autoComplete="name" icon={FiUser} label="Full name" onChange={update('name')} placeholder="Your name" value={form.name} /><Field autoComplete="email" icon={FiMail} label="Email address" onChange={update('email')} placeholder="you@example.com" value={form.email} /><label className="auth-field"><span>Password</span><div className="auth-input-wrap"><FiLock aria-hidden="true" /><input autoComplete="new-password" placeholder="Create a strong password" type={show ? 'text' : 'password'} value={form.password} onChange={update('password')} /><button aria-label={show ? 'Hide password' : 'Show password'} className="password-toggle" onClick={() => setShow(!show)} type="button">{show ? <FiEyeOff /> : <FiEye />}</button></div><small>At least 8 characters, including uppercase, lowercase, and a number.</small></label><label className="auth-field"><span>Confirm password</span><div className="auth-input-wrap"><FiLock aria-hidden="true" /><input autoComplete="new-password" placeholder="Repeat your password" type={show ? 'text' : 'password'} value={form.confirm} onChange={update('confirm')} /></div></label><button className="auth-submit" disabled={submitting} type="submit">{submitting ? 'Creating your account…' : 'Create account'} {!submitting && <FiArrowRight />}</button><p className="auth-switch">Already a member? <Link to="/login">Sign in</Link></p></form></AuthShell>
}
